version: '2'
services:
  web:
    build: .
    command: npm start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgres://qwertup:buffered07@127.0.0.1:5432/node_api_dev"

  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: qwertup
      POSTGRES_PASSWORD: buffered07
      POSTGRES_DB: node_api_dev